import jwt

# Sostituisci con il tuo access token
access_token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5WFFEUUZmNERaTllCSnpPcU42YWNJUm0zeWVEaVFqbUxESUhtbEJVR25JIn0.eyJqdGkiOiI2Y2UwYmEzNy05NjJlLTQ4YzItODBkNC0wNjVkZGY2MmUxNzgiLCJleHAiOjIwNDczNjY0MzksIm5iZiI6MCwiaWF0IjoxNzMyMDA2NDM5LCJpc3MiOiJodHRwczovL2F1dGhxYS5naW9iYnkuY29tL2F1dGgvcmVhbG1zL2FwaS1zZXJ2ZXIiLCJhdWQiOiJLUkUyMDIzMDkyMi1zYi1rcmVhY2FzYSIsInN1YiI6ImY6ZGFjYzM0MDUtOWQ1ZS00NWE0LWI1N2MtYTBmOTljMTAzZWQ2Ojc5MzAzfDEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJLUkUyMDIzMDkyMi1zYi1rcmVhY2FzYSIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjkwYjQ3ZDhkLTI3NTgtNDBmYS04MjU0LWRjYjdiOWE0NWE5OCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7fSwiaWRVc2VyIjoiMSIsImlkQ29tcGFueSI6Ijc5MzAzIiwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1c2VyIl19.abrDmVa_Tj7MGZphBg4McKjWfs9leylhto6fTJJ0yysGcSSCWl927eFlDsatO-KCY8qaFQzbyGNyzA5DkP5wKYMWMM0kQgPiEWdtc_qtLirVZVyGLdsJhRVnvKMapCA7ik_VSzBUTuKE8qJj5zqsVHYabCuMGzARniNq5nMda3DeeodrD4o-jThmsNYY_hDi9MZGakSrhlNnhgfOaB45dVcjEP0Px_7CR2iu9FlHadka_JBq98cVluwXEQ58wULVVqHIQgm0XyVZrDibaIcfV9L6rLM2GUM6EHAYxjRcmoLUYu9q2mtoCGJMdPX0HHW6gn-llCrn1Mca45-5ye_V4g"

# Decodifica senza verificare la firma (non serve la chiave segreta per leggere i dati)
decoded_payload = jwt.decode(access_token, options={"verify_signature": False})

# Estrai l'idCompany
id_company = decoded_payload.get("idCompany")
print("ID Company:", id_company)